### ISSUE TITLE
Shader Glitches

### ISSUE THREAD

**Issue by pietru2004** [Ombarus/pcg_planet_yt#3]
Hello I really like the tutorial on how to make planet, but after messing around with code rewritten from videos and creating multiple planets I found that there is some kind of shader problem. I mean the planets tend to get shader texture/colour/biome of last created planet.

Example - snow planet got desert planet skin
![obraz](https://user-images.githubusercontent.com/51274570/137622853-0e1e274a-ebe9-4f0a-9e1a-fd287ce0adb9.png)

Additionally: Shader is saved on disk.

**Comment by pietru2004** [comment]
I sort of found fix for people who have saved shader on disk

At PlanetMeshFace _update_mesh function.
`var shad_mat = ShaderMaterial.new()`
`shad_mat.shader=load("shader_load_path")`
`self.material_override=shad_mat`

![obraz](https://user-images.githubusercontent.com/51274570/137625875-373a1e38-11eb-4bba-94ca-b088ef21e854.png)

**Comment by Ombarus** [comment]
Materials and Shader are resources in Godot and they are shared (that's how we can set a single material to all the faces) But that means they are also shared between planets. If you want multiple planets with different material you're going to have to duplicate the shader. What you're doing might work. You might also want to take a look at the duplicate() method.
